SOURCES_LABELS = {
    "code": "Code",
    "bdd": "Base de données",
    "observabilite": "Observabilité",
    "incidents": "Incidents & changements",
    "documentation": "Documentation",
}

TWINS = [
    {"id": "paiements", "nom": "Paiements", "domaine": "Paiement", "mission": "Orchestre les transactions du parcours de paiement", "proprietaire": "Équipe Checkout — L. Marchand", "environnement": "production", "statut": "actif", "autonomie": "supervisé", "couverture": 92, "fraicheur": "il y a 3 min", "sante": "dégradé", "position": {"x": 620, "y": 300}, "sources": {"code": True, "bdd": True, "observabilite": True, "incidents": True, "documentation": True}},
    {"id": "facturation", "nom": "Facturation", "domaine": "Paiement", "mission": "Produit les factures et pilote la clôture quotidienne", "proprietaire": "Équipe Finance — A. Keita", "environnement": "production", "statut": "actif", "autonomie": "supervisé", "couverture": 81, "fraicheur": "il y a 12 min", "sante": "nominal", "position": {"x": 500, "y": 460}, "sources": {"code": True, "bdd": True, "observabilite": True, "incidents": False, "documentation": True}},
    {"id": "comptes", "nom": "Comptes", "domaine": "Client", "mission": "Gère les comptes clients, leurs soldes et leur historique", "proprietaire": "Équipe Client — M. Diallo", "environnement": "production", "statut": "actif", "autonomie": "supervisé", "couverture": 88, "fraicheur": "il y a 1 min", "sante": "nominal", "position": {"x": 140, "y": 240}, "sources": {"code": True, "bdd": True, "observabilite": True, "incidents": True, "documentation": True}},
    {"id": "identite", "nom": "Identité", "domaine": "Client", "mission": "Authentifie les clients et gère leurs sessions", "proprietaire": "Équipe Client — M. Diallo", "environnement": "production", "statut": "actif", "autonomie": "restreint", "couverture": 76, "fraicheur": "il y a 25 min", "sante": "nominal", "position": {"x": 180, "y": 420}, "sources": {"code": True, "bdd": True, "observabilite": True, "incidents": False, "documentation": False}},
    {"id": "fraude", "nom": "Fraude", "domaine": "Risque", "mission": "Évalue le risque de fraude en temps réel sur chaque transaction", "proprietaire": "Équipe Risque — S. Petit", "environnement": "production", "statut": "actif", "autonomie": "supervisé", "couverture": 84, "fraicheur": "il y a 2 min", "sante": "dégradé", "position": {"x": 1000, "y": 220}, "sources": {"code": True, "bdd": True, "observabilite": True, "incidents": True, "documentation": False}},
    {"id": "conformite", "nom": "Conformité", "domaine": "Risque", "mission": "Vérifie les obligations réglementaires des flux financiers", "proprietaire": "Équipe Risque — S. Petit", "environnement": "production", "statut": "en construction", "autonomie": "aucune", "couverture": 43, "fraicheur": "il y a 2 h", "sante": "inconnu", "position": {"x": 1080, "y": 380}, "sources": {"code": True, "bdd": False, "observabilite": False, "incidents": True, "documentation": False}},
    {"id": "support", "nom": "Support", "domaine": "Support", "mission": "Gère les demandes, tickets et macros de remboursement clients", "proprietaire": "Équipe Care — J. Morel", "environnement": "production", "statut": "actif", "autonomie": "supervisé", "couverture": 62, "fraicheur": "il y a 1 h", "sante": "nominal", "position": {"x": 990, "y": 570}, "sources": {"code": True, "bdd": False, "observabilite": True, "incidents": True, "documentation": False}},
    {"id": "notifications", "nom": "Notifications", "domaine": "Support", "mission": "Envoie les alertes et messages aux clients", "proprietaire": "Équipe Care — J. Morel", "environnement": "production", "statut": "actif", "autonomie": "restreint", "couverture": 71, "fraicheur": "il y a 18 min", "sante": "nominal", "position": {"x": 1090, "y": 690}, "sources": {"code": True, "bdd": True, "observabilite": True, "incidents": False, "documentation": False}},
    {"id": "commandes", "nom": "Commandes", "domaine": "Opérations", "mission": "Suit le cycle de vie des commandes de bout en bout", "proprietaire": "Équipe Ops — R. Fabre", "environnement": "production", "statut": "actif", "autonomie": "supervisé", "couverture": 79, "fraicheur": "il y a 7 min", "sante": "nominal", "position": {"x": 140, "y": 630}, "sources": {"code": True, "bdd": True, "observabilite": True, "incidents": True, "documentation": False}},
    {"id": "logistique", "nom": "Logistique", "domaine": "Opérations", "mission": "Pilote la préparation et l'expédition des commandes", "proprietaire": "Équipe Ops — R. Fabre", "environnement": "production", "statut": "observation", "autonomie": "aucune", "couverture": 51, "fraicheur": "il y a 3 h", "sante": "inconnu", "position": {"x": 240, "y": 740}, "sources": {"code": True, "bdd": True, "observabilite": False, "incidents": False, "documentation": False}},
    {"id": "portail-web", "nom": "Portail Web", "domaine": "Distribution", "mission": "Expose le parcours d'achat aux clients web", "proprietaire": "Équipe Digital — C. Nguyen", "environnement": "production", "statut": "actif", "autonomie": "restreint", "couverture": 68, "fraicheur": "il y a 33 min", "sante": "nominal", "position": {"x": 500, "y": 60}, "sources": {"code": True, "bdd": False, "observabilite": True, "incidents": False, "documentation": True}},
    {"id": "api-gateway", "nom": "API Gateway", "domaine": "Distribution", "mission": "Point d'entrée unique de toutes les API du SI", "proprietaire": "Équipe Plateforme — D. Roy", "environnement": "production", "statut": "actif", "autonomie": "supervisé", "couverture": 90, "fraicheur": "il y a 4 min", "sante": "nominal", "position": {"x": 700, "y": 90}, "sources": {"code": True, "bdd": True, "observabilite": True, "incidents": True, "documentation": True}},
]

REGIONS = [
    {"id": "reg-distribution", "label": "Distribution", "x": 440, "y": 0, "w": 460, "h": 190, "couleur": "#F0ABFC"},
    {"id": "reg-paiement", "label": "Paiement", "x": 440, "y": 230, "w": 420, "h": 320, "couleur": "#3B82F6"},
    {"id": "reg-client", "label": "Client", "x": 60, "y": 170, "w": 340, "h": 340, "couleur": "#34D399"},
    {"id": "reg-risque", "label": "Risque", "x": 960, "y": 150, "w": 340, "h": 320, "couleur": "#F87171"},
    {"id": "reg-support", "label": "Support", "x": 940, "y": 500, "w": 380, "h": 290, "couleur": "#FBBF24"},
    {"id": "reg-operations", "label": "Opérations", "x": 60, "y": 560, "w": 340, "h": 260, "couleur": "#38BDF8"},
]

RELATIONS = [
    {"id": "r1", "source": "portail-web", "cible": "api-gateway", "type": "structurante", "active": True, "label": "appels HTTPS"},
    {"id": "r2", "source": "api-gateway", "cible": "paiements", "type": "structurante", "active": True, "label": "POST /payments"},
    {"id": "r3", "source": "api-gateway", "cible": "comptes", "type": "structurante", "active": False},
    {"id": "r4", "source": "paiements", "cible": "comptes", "type": "structurante", "active": True, "label": "débit / crédit"},
    {"id": "r5", "source": "paiements", "cible": "fraude", "type": "structurante", "active": True, "label": "contrôles synchrones"},
    {"id": "r6", "source": "paiements", "cible": "support", "type": "decouverte", "active": True, "label": "relation non documentée", "confiance": 82},
    {"id": "r7", "source": "paiements", "cible": "facturation", "type": "structurante", "active": False, "label": "PaymentSettled"},
    {"id": "r8", "source": "commandes", "cible": "paiements", "type": "structurante", "active": False},
    {"id": "r9", "source": "commandes", "cible": "logistique", "type": "structurante", "active": True, "label": "préparation"},
    {"id": "r10", "source": "support", "cible": "notifications", "type": "structurante", "active": False},
    {"id": "r11", "source": "comptes", "cible": "identite", "type": "structurante", "active": False},
    {"id": "r12", "source": "fraude", "cible": "conformite", "type": "structurante", "active": False},
    {"id": "r13", "source": "facturation", "cible": "comptes", "type": "secondaire", "active": False},
]

SITUATIONS = [
    {
        "id": "sit-latence-paiements",
        "type": "incident",
        "titre": "Latence du parcours de paiement en hausse depuis 14 h 32",
        "resume": "Le temps de réponse du parcours de paiement a dérivé de 240 ms à 1,9 s en douze minutes. L'impact client est visible dans Support depuis 14 h 39.",
        "priorite": "critique",
        "statut": "active",
        "score": 94,
        "detectee": "aujourd'hui · 14 h 32",
        "question": "Pourquoi le paiement ralentit-il ?",
        "jumeaux": ["paiements", "comptes", "fraude", "support"],
        "aurora_recommandation": "Je recommande de consulter Paiements, Comptes, Fraude et Support.",
        "indicateurs": {"confiance": 78, "couverture": 86, "fraicheur": "il y a 2 min", "contradictions": 1},
        "chronologie": [
            {"heure": "14 h 32", "texte": "Dérive de latence détectée sur le parcours de paiement", "jumeau": "paiements", "nature": "signal"},
            {"heure": "14 h 34", "texte": "Hausse des appels vers Comptes (+38 %)", "jumeau": "comptes", "nature": "signal"},
            {"heure": "14 h 36", "texte": "Augmentation des contrôles synchrones de Fraude", "jumeau": "fraude", "nature": "signal"},
            {"heure": "14 h 39", "texte": "Premiers tickets Support liés aux délais de paiement", "jumeau": "support", "nature": "signal"},
            {"heure": "14 h 44", "texte": "Incident historique similaire retrouvé (INC-4471, mars 2026)", "jumeau": "support", "nature": "preuve"},
        ],
        "hypotheses": [
            {"id": "h1", "texte": "Saturation du service Comptes", "confiance": 34,
             "pour": ["Hausse des appels Comptes à 14 h 34", "Latence de lecture des soldes en hausse de 12 %"],
             "contre": ["CPU et mémoire de Comptes stables", "Aucune file d'attente saturée"],
             "verifications": ["Comparer avec les métriques de la semaine passée"]},
            {"id": "h2", "texte": "Changement de comportement des contrôles Fraude", "confiance": 78,
             "pour": ["Contrôles synchrones passés de 1,2 à 3,4 par transaction", "Règle R-118 modifiée aujourd'hui à 13 h 58", "4 traces Datadog montrent l'attente sur Fraude"],
             "contre": ["Fraude signale un comportement nominal de son point de vue"],
             "verifications": ["Confirmer le déploiement de R-118 avec l'équipe Risque"]},
            {"id": "h3", "texte": "Dépendance indirecte non documentée Paiements ↔ Support", "confiance": 66,
             "pour": ["82 % des périodes de ralentissement précèdent des demandes Support", "Aucune relation déclarée dans les sources connectées"],
             "contre": ["Aucun appel direct observé dans les traces"],
             "verifications": ["Analyser les files de messages communes"]},
            {"id": "h4", "texte": "Changement récent dans Paiements", "confiance": 41,
             "pour": ["Version 4.17.2 déployée à 11 h 20"],
             "contre": ["Latence stable entre 11 h 20 et 14 h 32"],
             "verifications": ["Rejouer les requêtes témoins sur la version précédente"]},
        ],
        "contributions": [
            {"jumeau": "Paiements", "domaine": "Paiement", "texte": "Augmentation du temps d'attente sur les appels synchrones sortants."},
            {"jumeau": "Fraude", "domaine": "Risque", "texte": "Hausse du nombre de contrôles par transaction depuis la règle R-118."},
            {"jumeau": "Comptes", "domaine": "Client", "texte": "Comportement stable malgré la hausse des appels."},
            {"jumeau": "Support", "domaine": "Support", "texte": "Apparition de demandes clients liées aux délais de paiement."},
        ],
        "preuves": [
            {"source": "Datadog", "detail": "4 traces montrant l'attente synchrone sur Fraude"},
            {"source": "Splunk", "detail": "3 observations de dérive sur le parcours paiement"},
            {"source": "Code", "detail": "2 éléments : règle R-118 et appel synchrone fraud.check"},
            {"source": "ServiceNow", "detail": "Incident INC-4471 (mars 2026) aux symptômes identiques"},
        ],
        "synthese": "Le ralentissement semble provenir d'une augmentation des contrôles synchrones effectués par Fraude depuis la modification de la règle R-118 à 13 h 58. La relation émergente avec Support amplifie l'impact ressenti par les clients. Un incident similaire (INC-4471) avait été résolu en rendant le contrôle R-118 asynchrone.",
        "actions_proposees": ["Basculer le contrôle R-118 en mode asynchrone", "Créer un dossier de changement dans Change Lab", "Surveiller la relation Paiements ↔ Support"],
        "decision": None,
    },
    {
        "id": "sit-relation-emergente",
        "type": "decouverte",
        "titre": "Relation émergente : ralentissements Paiements → demandes Support",
        "resume": "Les ralentissements de Paiements précèdent une augmentation des demandes Support dans 82 % des périodes observées. Aucune relation n'est documentée entre ces deux applications.",
        "priorite": "haute",
        "statut": "active",
        "score": 82,
        "detectee": "aujourd'hui · 13 h 05",
        "question": "Les ralentissements de Paiements provoquent-ils les demandes Support ?",
        "jumeaux": ["paiements", "support"],
        "aurora_recommandation": "Je recommande de consulter Paiements et Support.",
        "indicateurs": {"confiance": 82, "couverture": 64, "fraicheur": "il y a 9 min", "contradictions": 0},
        "chronologie": [
            {"heure": "13 h 05", "texte": "Corrélation détectée sur 23 périodes de 15 minutes", "jumeau": "paiements", "nature": "signal"},
            {"heure": "13 h 12", "texte": "Aucune relation déclarée trouvée dans les sources connectées", "jumeau": "support", "nature": "preuve"},
        ],
        "hypotheses": [
            {"id": "h1", "texte": "Corrélation réelle via une file de messages commune", "confiance": 66,
             "pour": ["82 % des périodes concordantes", "Délai moyen de 7 minutes entre signal et tickets"],
             "contre": ["Aucun appel direct dans les traces"],
             "verifications": ["Analyser les files de messages communes"]},
        ],
        "contributions": [],
        "preuves": [{"source": "Splunk", "detail": "23 périodes concordantes sur 28 observées"}],
        "synthese": "La corrélation est forte mais le mécanisme reste à confirmer : aucune relation n'est documentée entre Paiements et Support.",
        "actions_proposees": ["Créer une investigation", "Surveiller la relation"],
        "decision": None,
    },
    {
        "id": "sit-changement-settlement",
        "type": "changement",
        "titre": "Changement à risque : remplacer settlementDate par settlementTimestamp",
        "resume": "Le changement proposé sur l'événement PaymentSettled touche trois consommateurs directs. Un incident similaire en 2025 a rompu la réconciliation pendant 6 heures.",
        "priorite": "haute",
        "statut": "active",
        "score": 76,
        "detectee": "aujourd'hui · 09 h 12",
        "jumeaux": ["paiements", "facturation", "comptes", "support"],
        "aurora_recommandation": "Je recommande de simuler ce changement dans Change Lab.",
        "indicateurs": {"confiance": 85, "couverture": 79, "fraicheur": "il y a 14 min", "contradictions": 0},
        "chronologie": [],
        "hypotheses": [],
        "contributions": [],
        "preuves": [{"source": "ServiceNow", "detail": "Incident INC-3910 : renommage de champ en 2025, 6 h de rupture"}],
        "synthese": "Le remplacement direct est cassant pour les trois consommateurs directs. Un scénario rétrocompatible est disponible dans Change Lab.",
        "actions_proposees": ["Ouvrir dans Change Lab"],
        "decision": None,
    },
    {
        "id": "sit-anomalie-fraude",
        "type": "anomalie",
        "titre": "Comportement inhabituel : hausse des contrôles synchrones Fraude",
        "resume": "Le nombre de contrôles synchrones par transaction est passé de 1,2 à 3,4 depuis la modification de la règle R-118 à 13 h 58.",
        "priorite": "moyenne",
        "statut": "active",
        "score": 61,
        "detectee": "aujourd'hui · 14 h 36",
        "question": "Pourquoi les contrôles Fraude ont-ils augmenté ?",
        "jumeaux": ["fraude", "paiements"],
        "aurora_recommandation": "Je recommande de consulter Fraude et Paiements.",
        "indicateurs": {"confiance": 74, "couverture": 71, "fraicheur": "il y a 5 min", "contradictions": 1},
        "chronologie": [
            {"heure": "13 h 58", "texte": "Règle R-118 modifiée par l'équipe Risque", "jumeau": "fraude", "nature": "signal"},
            {"heure": "14 h 36", "texte": "Contrôles synchrones × 2,8 par transaction", "jumeau": "fraude", "nature": "signal"},
        ],
        "hypotheses": [
            {"id": "h1", "texte": "La règle R-118 déclenche des contrôles supplémentaires", "confiance": 78,
             "pour": ["Corrélation temporelle exacte avec la modification", "4 traces Datadog concordantes"],
             "contre": ["Fraude signale un comportement nominal"],
             "verifications": ["Confirmer le périmètre de R-118 avec l'équipe Risque"]},
        ],
        "contributions": [],
        "preuves": [{"source": "Datadog", "detail": "4 traces d'attente synchrone"}, {"source": "Code", "detail": "Règle R-118 modifiée à 13 h 58"}],
        "synthese": "La modification de la règle R-118 explique très probablement la hausse des contrôles synchrones.",
        "actions_proposees": ["Rejoindre l'investigation latence"],
        "decision": None,
    },
    {
        "id": "sit-propagation",
        "type": "incident",
        "titre": "Incident en propagation : Commandes → Logistique",
        "resume": "Des ruptures de stock signalées en cascade depuis Commandes ralentissent la préparation Logistique. Propagation limitée au domaine Opérations pour l'instant.",
        "priorite": "haute",
        "statut": "surveillée",
        "score": 73,
        "detectee": "aujourd'hui · 11 h 47",
        "jumeaux": ["commandes", "logistique"],
        "aurora_recommandation": "Je recommande de consulter Commandes et Logistique.",
        "indicateurs": {"confiance": 69, "couverture": 55, "fraicheur": "il y a 22 min", "contradictions": 0},
        "chronologie": [
            {"heure": "11 h 47", "texte": "Ruptures de stock signalées en cascade", "jumeau": "commandes", "nature": "signal"},
            {"heure": "11 h 58", "texte": "File de préparation Logistique en hausse (+64 %)", "jumeau": "logistique", "nature": "signal"},
            {"heure": "12 h 20", "texte": "Propagation contenue au domaine Opérations", "jumeau": "commandes", "nature": "preuve"},
        ],
        "hypotheses": [],
        "contributions": [],
        "preuves": [],
        "synthese": "Propagation contenue. La connaissance du jumeau Logistique (51 %) limite l'analyse : une phase d'observation supplémentaire est recommandée.",
        "actions_proposees": ["Surveiller"],
        "decision": None,
    },
    {
        "id": "sit-connaissance-support",
        "type": "connaissance",
        "titre": "Connaissance du jumeau Support devenue obsolète",
        "resume": "La couverture de connaissance de Support est tombée à 62 % : base de connaissances non connectée et documentation non rafraîchie depuis 47 jours.",
        "priorite": "moyenne",
        "statut": "active",
        "score": 55,
        "detectee": "hier · 17 h 40",
        "jumeaux": ["support"],
        "aurora_recommandation": "Je recommande de connecter la base de connaissances Support.",
        "indicateurs": {"confiance": 90, "couverture": 62, "fraicheur": "il y a 1 h", "contradictions": 0},
        "chronologie": [],
        "hypotheses": [],
        "contributions": [],
        "preuves": [{"source": "Registry", "detail": "Couverture 62 %, documentation âgée de 47 jours"}],
        "synthese": "La fiabilité des réponses impliquant Support est réduite tant que la base de connaissances n'est pas connectée.",
        "actions_proposees": ["Ouvrir dans Registry"],
        "decision": None,
    },
    {
        "id": "sit-optimisation-facturation",
        "type": "optimisation",
        "titre": "Fenêtre d'optimisation : facturation différée possible",
        "resume": "La clôture quotidienne pourrait être décalée de 40 minutes sans impact sur les consommateurs, libérant des ressources en heure de pointe.",
        "priorite": "basse",
        "statut": "active",
        "score": 38,
        "detectee": "hier · 09 h 15",
        "jumeaux": ["facturation", "comptes"],
        "aurora_recommandation": "Je recommande de consulter Facturation et Comptes.",
        "indicateurs": {"confiance": 64, "couverture": 58, "fraicheur": "il y a 3 h", "contradictions": 0},
        "chronologie": [],
        "hypotheses": [],
        "contributions": [],
        "preuves": [],
        "synthese": "Optimisation à faible risque, à planifier hors période de clôture.",
        "actions_proposees": ["Planifier"],
        "decision": None,
    },
]

CHANGE_LAB = {
    "id": "principal",
    "changement": "Remplacer settlementDate par settlementTimestamp dans l'événement PaymentSettled",
    "perimetre": ["paiements", "facturation", "comptes", "support"],
    "consommateurs_directs": [
        {"jumeau": "Facturation", "domaine": "Paiement", "detail": "Lit settlementDate pour la clôture quotidienne"},
        {"jumeau": "Comptes", "domaine": "Client", "detail": "Affiche la date de règlement dans l'historique client"},
        {"jumeau": "Support", "domaine": "Support", "detail": "Macro de remboursement basée sur settlementDate"},
    ],
    "effets_indirects": [
        "Rapports de clôture décalés d'un jour si le fuseau horaire est mal converti",
        "Réconciliation comptable J+1 potentiellement rompue",
    ],
    "processus": ["Clôture quotidienne", "Remboursement client", "Réconciliation J+1"],
    "regles": ["R-077 : remboursement sous 48 h", "R-204 : clôture avant 23 h 00"],
    "incidents_similaires": [
        {"id": "INC-3910", "texte": "Renommage de champ en 2025 : 6 h de rupture de réconciliation"},
    ],
    "tests_recommandes": [
        "Test de réconciliation J+1 sur jeu historique",
        "Test de la macro de remboursement Support",
        "Vérification du fuseau horaire sur la clôture",
    ],
    "zones_non_couvertes": ["Export comptable mensuel (connaissance obsolète, 58 %)"],
    "scenarios": [
        {"nom": "Remplacement direct", "risque": "Élevé", "effort": "Faible", "compatibilite": "Faible", "note": "Cassant pour les trois consommateurs directs dès le déploiement.", "recommande": False},
        {"nom": "Double champ temporaire", "risque": "Faible", "effort": "Moyen", "compatibilite": "Élevée", "note": "Les deux champs coexistent pendant 4 semaines, puis retrait de settlementDate.", "recommande": True},
        {"nom": "Nouvelle version d'événement", "risque": "Moyen", "effort": "Élevé", "compatibilite": "Élevée", "note": "PaymentSettled v2 ; migration progressive des consommateurs.", "recommande": False},
    ],
}

PARCOURS = [
    {"id": "parcours-paiement", "nom": "Parcours de paiement", "etapes": ["portail-web", "api-gateway", "paiements", "fraude", "comptes", "facturation"]},
    {"id": "parcours-remboursement", "nom": "Parcours de remboursement", "etapes": ["support", "paiements", "comptes", "notifications"]},
]

ACTIVITE = [
    {"jumeau": "paiements", "texte": "Transaction validée en 312 ms", "nature": "trace"},
    {"jumeau": "fraude", "texte": "Contrôle R-118 exécuté (synchrone)", "nature": "signal"},
    {"jumeau": "support", "texte": "Nouveau ticket « délai de paiement »", "nature": "signal"},
    {"jumeau": "comptes", "texte": "Lecture de solde — 45 ms", "nature": "trace"},
    {"jumeau": "commandes", "texte": "Commande confirmée, paiement demandé", "nature": "trace"},
    {"jumeau": "api-gateway", "texte": "2 140 requêtes / minute", "nature": "trace"},
    {"jumeau": "notifications", "texte": "Alerte client envoyée", "nature": "trace"},
    {"jumeau": "facturation", "texte": "Écriture de clôture planifiée à 23 h 00", "nature": "trace"},
    {"jumeau": "identite", "texte": "Session client vérifiée", "nature": "trace"},
    {"jumeau": "logistique", "texte": "Préparation de commande démarrée", "nature": "trace"},
    {"jumeau": "paiements", "texte": "Latence p99 : 1,9 s (seuil : 800 ms)", "nature": "alerte"},
    {"jumeau": "support", "texte": "Corrélation détectée avec le ralentissement Paiements", "nature": "decouverte"},
    {"jumeau": "fraude", "texte": "File de contrôles : 212 en attente", "nature": "alerte"},
    {"jumeau": "conformite", "texte": "Apprentissage : 34 documents analysés", "nature": "trace"},
]

AURORA_SCRIPTS = [
    {
        "contexte": "radar",
        "mots_cles": ["prioritaire", "priorité", "pourquoi cette situation"],
        "reponse": "Cette situation est prioritaire car elle combine trois facteurs : une dérive rapide (240 ms → 1,9 s en 12 minutes), un impact client visible (tickets Support depuis 14 h 39) et un précédent historique (INC-4471, résolu en mars 2026). Son score de 94 la place en tête du flux.",
        "contributions": [
            {"jumeau": "Paiements", "domaine": "Paiement", "texte": "Vitesse de dérive inhabituelle sur la fenêtre de 12 minutes."},
            {"jumeau": "Support", "domaine": "Support", "texte": "Impact client confirmé par les premiers tickets."},
        ],
        "preuves": [
            {"source": "Datadog", "detail": "Courbe de latence p99 du parcours paiement"},
            {"source": "ServiceNow", "detail": "INC-4471 : signature identique en mars 2026"},
        ],
        "indicateurs": {"confiance": 88, "couverture": 86, "fraicheur": "il y a 2 min", "contradictions": 0},
    },
    {
        "contexte": "radar",
        "mots_cles": ["semaine", "changé", "change"],
        "reponse": "Trois changements notables cette semaine : la règle R-118 de Fraude (aujourd'hui 13 h 58), le déploiement de Paiements 4.17.2 (aujourd'hui 11 h 20) et l'apparition de la relation Paiements ↔ Support. Le premier est le plus susceptible d'expliquer la situation active.",
        "contributions": [
            {"jumeau": "Fraude", "domaine": "Risque", "texte": "R-118 modifiée à 13 h 58, 34 minutes avant la dérive."},
            {"jumeau": "Paiements", "domaine": "Paiement", "texte": "Version 4.17.2 stable pendant 3 heures avant la dérive."},
        ],
        "preuves": [{"source": "Code", "detail": "Historique des déploiements et règles sur 7 jours"}],
        "indicateurs": {"confiance": 81, "couverture": 78, "fraicheur": "il y a 4 min", "contradictions": 0},
    },
    {
        "contexte": "investigation",
        "mots_cles": ["ralentit", "paiement", "latence"],
        "reponse": "Le ralentissement semble provenir d'une augmentation des contrôles synchrones effectués par Fraude depuis la modification de la règle R-118 à 13 h 58.",
        "contributions": [
            {"jumeau": "Paiements", "domaine": "Paiement", "texte": "Augmentation du temps d'attente sur les appels sortants."},
            {"jumeau": "Fraude", "domaine": "Risque", "texte": "Hausse du nombre de contrôles par transaction."},
            {"jumeau": "Comptes", "domaine": "Client", "texte": "Comportement stable malgré la hausse des appels."},
            {"jumeau": "Support", "domaine": "Support", "texte": "Apparition de demandes liées aux délais de paiement."},
        ],
        "preuves": [
            {"source": "Datadog", "detail": "4 traces d'attente synchrone sur Fraude"},
            {"source": "Splunk", "detail": "3 observations de dérive"},
            {"source": "Code", "detail": "2 éléments : R-118 et fraud.check"},
            {"source": "ServiceNow", "detail": "1 incident similaire (INC-4471)"},
        ],
        "indicateurs": {"confiance": 78, "couverture": 86, "fraicheur": "il y a 2 min", "contradictions": 1},
    },
    {
        "contexte": "investigation",
        "mots_cles": ["antérieur", "compare", "incident", "historique"],
        "reponse": "L'hypothèse « contrôles Fraude » correspond à l'incident INC-4471 (12 mars 2026) : même signature (contrôles synchrones multipliés par 3), même tranche horaire. INC-4471 avait été résolu en basculant R-118 en mode asynchrone. En revanche, « saturation Comptes » ne correspond à aucun incident connu.",
        "contributions": [
            {"jumeau": "Support", "domaine": "Support", "texte": "INC-4471 retrouvé dans l'historique des incidents."},
            {"jumeau": "Fraude", "domaine": "Risque", "texte": "Signature de R-118 identique à celle de mars 2026."},
        ],
        "preuves": [{"source": "ServiceNow", "detail": "INC-4471 : résolution documentée (contrôle asynchrone)"}],
        "indicateurs": {"confiance": 82, "couverture": 74, "fraicheur": "il y a 6 min", "contradictions": 1},
    },
    {
        "contexte": "carte",
        "mots_cles": ["dépendances", "dependances", "critiques", "filtre"],
        "reponse": "Paiements possède trois dépendances critiques actives : Comptes (débit/crédit), Fraude (contrôles synchrones) et la relation non documentée vers Support. J'applique le filtre sur la carte.",
        "contributions": [
            {"jumeau": "Paiements", "domaine": "Paiement", "texte": "Trois flux sortants actifs sur la dernière heure."},
        ],
        "preuves": [{"source": "Observabilité", "detail": "Flux mesurés sur les 60 dernières minutes"}],
        "indicateurs": {"confiance": 91, "couverture": 80, "fraicheur": "il y a 1 min", "contradictions": 0},
        "action": {"label": "Appliquer le filtre sur la carte", "route": "/carte?focus=paiements"},
    },
    {
        "contexte": "carte",
        "mots_cles": ["périmètre", "perimetre", "justifie"],
        "reponse": "J'ai retenu Paiements (source du signal), Fraude (corrélation forte à 14 h 36), Comptes (hausse des appels à 14 h 34) et Support (impact client à 14 h 39). J'ai écarté Logistique et Facturation : aucune corrélation sur la période. Vous pouvez retirer un participant ou limiter la période.",
        "contributions": [],
        "preuves": [{"source": "Aurora", "detail": "Analyse de corrélation sur la fenêtre 14 h 30 – 14 h 45"}],
        "indicateurs": {"confiance": 86, "couverture": 83, "fraicheur": "il y a 3 min", "contradictions": 0},
    },
    {
        "contexte": "change-lab",
        "mots_cles": ["rétrocompatible", "retrocompatible", "scénario", "scenario", "propose"],
        "reponse": "Je recommande le scénario « Double champ temporaire » : settlementDate et settlementTimestamp coexistent pendant 4 semaines, les consommateurs migrent à leur rythme, puis l'ancien champ est retiré. Risque faible, effort moyen, compatibilité élevée. L'incident INC-3910 (rupture de réconciliation après un renommage direct en 2025) plaide contre le remplacement direct.",
        "contributions": [
            {"jumeau": "Facturation", "domaine": "Paiement", "texte": "Compatible avec la clôture quotidienne sans modification immédiate."},
            {"jumeau": "Support", "domaine": "Support", "texte": "La macro de remboursement migre sans interruption."},
        ],
        "preuves": [{"source": "ServiceNow", "detail": "INC-3910 : échec du remplacement direct en 2025"}],
        "indicateurs": {"confiance": 85, "couverture": 79, "fraicheur": "il y a 11 min", "contradictions": 0},
    },
    {
        "contexte": "change-lab",
        "mots_cles": ["tests", "test"],
        "reponse": "Trois tests sont recommandés avant ce changement : réconciliation J+1 sur jeu historique, macro de remboursement Support, et vérification du fuseau horaire sur la clôture. La zone « export comptable mensuel » n'est pas couverte (connaissance à 58 %) : je recommande un test manuel complémentaire.",
        "contributions": [
            {"jumeau": "Comptes", "domaine": "Client", "texte": "Jeu historique de réconciliation disponible."},
        ],
        "preuves": [{"source": "Change Lab", "detail": "Analyse des processus touchés et de leurs règles"}],
        "indicateurs": {"confiance": 80, "couverture": 72, "fraicheur": "il y a 11 min", "contradictions": 0},
    },
    {
        "contexte": "registry",
        "mots_cles": ["support", "incomplète", "incomplete", "connaissance"],
        "reponse": "La connaissance du jumeau Support est à 62 % car deux sources ne sont pas connectées : la base de connaissances interne et l'historique des macros de remboursement. De plus, sa documentation n'a pas été rafraîchie depuis 47 jours. Je recommande de connecter la base de connaissances puis de relancer une phase d'observation.",
        "contributions": [
            {"jumeau": "Support", "domaine": "Support", "texte": "Signale lui-même des zones non couvertes dans ses réponses."},
        ],
        "preuves": [{"source": "Registry", "detail": "État des sources et fraîcheur de la documentation"}],
        "indicateurs": {"confiance": 90, "couverture": 62, "fraicheur": "il y a 1 h", "contradictions": 0},
    },
    {
        "contexte": "registry",
        "mots_cles": ["admettre", "priorité", "priorite", "quel jumeau"],
        "reponse": "Je recommande d'admettre Conformité en priorité : c'est le seul domaine réglementaire sans jumeau actif, et deux situations récentes mentionnent des règles de conformité. Logistique peut attendre la fin de sa phase d'observation (couverture 51 %).",
        "contributions": [],
        "preuves": [{"source": "Registry", "detail": "Couverture par domaine et demandes en attente"}],
        "indicateurs": {"confiance": 77, "couverture": 69, "fraicheur": "il y a 20 min", "contradictions": 0},
    },
    {
        "contexte": "global",
        "mots_cles": ["mesh", "sais-tu", "que sais"],
        "reponse": "Le Mesh compte 12 jumeaux : 9 actifs, 1 en observation, 1 en construction et 1 en cours d'apprentissage. La couverture moyenne est de 74 %. Deux zones sont fragiles : Support (62 %) et l'export comptable (58 %).",
        "contributions": [],
        "preuves": [{"source": "Registry", "detail": "État d'admission et couverture des 12 jumeaux"}],
        "indicateurs": {"confiance": 93, "couverture": 74, "fraicheur": "il y a 1 min", "contradictions": 0},
    },
]

AURORA_FALLBACK = {
    "reponse": "Je n'ai pas encore assez de connaissances pour répondre précisément à cette question. Connaissances manquantes : traces des files de messages communes et documentation Support (non rafraîchie depuis 47 jours). Essayez l'une des questions suggérées.",
    "contributions": [],
    "preuves": [],
    "indicateurs": {"confiance": 24, "couverture": 41, "fraicheur": "il y a 2 min", "contradictions": 0},
}

AURORA_SUGGESTIONS = {
    "radar": ["Pourquoi cette situation est-elle prioritaire ?", "Qu'est-ce qui a changé cette semaine ?"],
    "investigation": ["Pourquoi le paiement ralentit-il ?", "Compare cette hypothèse aux incidents antérieurs."],
    "change-lab": ["Propose un scénario rétrocompatible.", "Quels tests sont recommandés ?"],
    "carte": ["Montre uniquement les dépendances critiques de Paiements.", "Justifie le périmètre de l'investigation."],
    "registry": ["Pourquoi la connaissance de Support est-elle incomplète ?", "Quel jumeau admettre en priorité ?"],
    "global": ["Que sais-tu du Mesh ?"],
}

DEMO_ACTES = [
    {"acte": 1, "titre": "Le signal", "route": "/", "texte": "14 h 32. Le Radar détecte une dérive de latence dans Paiements et la place en tête du flux, devant tout le reste."},
    {"acte": 2, "titre": "La Situation", "route": "/investigations", "texte": "Méridian crée une Situation et rassemble automatiquement Paiements, Comptes, Fraude et Support — sans demander à l'utilisateur de sélectionner les jumeaux."},
    {"acte": 3, "titre": "L'investigation", "route": "/investigations/sit-latence-paiements", "texte": "Aurora construit quatre hypothèses et croise les sources : Datadog, Splunk, code et ServiceNow. Chaque hypothèse porte ses preuves pour et contre."},
    {"acte": 4, "titre": "La découverte", "route": "/carte?mode=situation&situation=sit-latence-paiements", "texte": "Sur la carte, une relation non documentée entre Paiements et Support apparaît — absente de toutes les sources déclarées."},
    {"acte": 5, "titre": "L'explication", "route": "/investigations/sit-latence-paiements", "texte": "L'utilisateur ouvre les preuves et retrouve l'incident INC-4471, résolu en mars 2026 en rendant le contrôle R-118 asynchrone."},
    {"acte": 6, "titre": "La décision", "route": "/change-lab", "texte": "Méridian propose une action et montre son rayon d'impact dans Change Lab : trois scénarios comparés, un recommandé."},
    {"acte": 7, "titre": "La révélation", "route": "/carte?mode=territoire", "texte": "Zoom arrière : toute cette compréhension vient d'un Mesh de jumeaux applicatifs autonomes qui observent le SI en permanence."},
]
